#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("InAnger.Droid.Resource", IsApplication=true)]

namespace InAnger.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::InAnger.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::InAnger.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int accessories = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int accessoriesbg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bama1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bama2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int bama3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bama4 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bama5 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bama6 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bama7 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bama8 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bama9 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int chat = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int children = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int childrenbg = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Chipotle = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dome = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int face = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int fashion = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int fashionbg = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int food = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int foodbg = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Garlic = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int gifts = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int giftsbg = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Habanero = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int hours = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int hoursbg = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int housewares = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int housewaresbg = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int icon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int Jalapeno = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int luggage = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int luggagebg = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int Overlay = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int pin = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int pindrop = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int restrooms = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int restroomsbg = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int services = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int servicesbg = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int settings = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int shoes = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int shoesbg = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int southmountain = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Tabasco = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int vending = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int vendingbg = 2130837550;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030001
			public const int ApplicationName = 2130903041;
			
			// aapt resource value: 0x7f030000
			public const int Hello = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
